//
// Created by Ardrass on 010, 10.07.2024.
//

#ifndef OURPAINT_ENUMS_H
#define OURPAINT_ENUMS_H
enum Element {
    ET_POINT, ET_SECTION, ET_CIRCLE
};
enum Requirement {
    ET_POINTONPOINT,
    ET_POINTPOINTDIST,
    ET_POINTONSECTION,
    ET_POINTSECTIONDIST,
    ET_SECTIONCIRCLEDIST,
    ET_SECTIONSECTIONDISTPARALLEL,
    ET_SECTIONSECTIONPERPENDICULAR,
    ET_SECTIONSECTIONANGEL,
    ET_SECTIONSECTIONANGELEQ,
    ET_SECTIONONCIRCLE,
    ET_SECTIONINCIRCLE
};
#endif //OURPAINT_ENUMS_H
